name: test

on:
  workflow_dispatch:

jobs:
  dispatch_reusable_workflow:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Reusable Workflow
        run: |
          gh workflow run --repo=msargent-dev/dynamic-exec concurrency-dispatch.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure necessary permissions
